### ISSUE TITLE
Failed to read zip - dir structure incorrect?

### ISSUE THREAD

**Issue by jape42** [bigbrozer/kodi-steamlink-launcher#3]
downloaded the zip file and tried to install it on pi 3b+ running raspbian and kodi.

got "unable to read zip" in kodi logs

08:31:16.892 T:1911697408   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
08:31:17.059 T:1911697408   DEBUG: OnKey: return (0xf00d) pressed, action is Select
08:31:17.059 T:1911697408   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
08:31:17.305 T:1911697408   DEBUG: ------ Window Deinit (FileBrowser.xml) ------
08:31:17.327 T:1911697408   DEBUG: CAddonInstaller: installing from zip '/home/kodi/Downloads/steamlink-launcher-0.0.1.zip'
08:31:17.339 T:1911697408   ERROR: Failed to read 'zip://%2fhome%2fkodi%2fDownloads%2fsteamlink-launcher-0.0.1.zip/kodi-steamlink-launcher-0.0.1/addon.xml'
08:31:17.340 T:1911697408   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
08:31:17.361 T:1911697408   DEBUG: ------ Window Init (DialogNotification.xml) ------
08:31:23.103 T:1911697408   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
08:31:30.558 T:1551340288   DEBUG: [plugin.video.youtube] HTTPServer: Request uri path |/ping|
08:31:30.559 T:1551340288   DEBUG: [plugin.video.youtube] HTTPServer: Connection from |127.0.| Local range: |True|
08:31:30.571 T:1699177216   DEBUG: [plugin.video.youtube] HTTPServer: Ping |127.0.0.1:50152| |204|

os info:

kodi@vcr:~/Downloads $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

This is what's in the zip file I downloaded:

kodi@vcr:~/Downloads $ find kodi-steamlink-launcher-0.0.1/
kodi-steamlink-launcher-0.0.1/
kodi-steamlink-launcher-0.0.1/.gitignore
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/resources
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/resources/screenshot.png
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/resources/lib
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/resources/lib/start.sh
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/resources/icon.png
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/resources/fanart.jpg
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/LICENSE.txt
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/addon.py
kodi-steamlink-launcher-0.0.1/plugin.program.steamlink/addon.xml
kodi-steamlink-launcher-0.0.1/Makefile
kodi-steamlink-launcher-0.0.1/README.md

**Comment by jape42** [comment]
moving the files up a directory and rezipping the result seemed to work for me.

**Comment by bigbrozer** [comment]
Yes. It seems the ZIP GitHub is providing is not correct for Kodi import. It should not have an extra directory as parent but immediatly see `plugin.program.steamlink/` folder. I will look at it to provide correct ZIP through **Releases**.

**Comment by bigbrozer** [comment]
Released [v0.0.2](https://github.com/bigbrozer/kodi-steamlink-launcher/releases/tag/v0.0.2). Please use the ZIP provided in this release. Before updating, take care for the new requirements in `README` ! I will try to make it work as mush as possible on any config but this is still v0.0.x releases ;-)

**Comment by jape42** [comment]
Tested with 0.02 release.  No problems observed with installation of zip.  Launching of steamlink worked as expected from within kodi.  Couldn't figure out how to exit steam link app and return to kodi though.

**Comment by bigbrozer** [comment]
I'm using a XBox 360 controller, hitting **B** on the steamlink home screen (where you can select computers) will exit to kodi. Maybe **Esc** from a keyboard should do the trick too...

**Comment by jape42** [comment]
Thanks.  real keyboard escape allows exit and kodi is resumed.  Very nice work.  

My remote mouse/keybaord device must not be sending an escape, though it is processed as a "back" operation within kodi (but not steamlink).
